backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/pages/home.yaml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Hero Heading"
            name: "hero_heading"
            widget: "string"
          - label: "Hero Subheading"
            name: "hero_subheading"
            widget: "string"
      - label: "Blog Page"
        name: "blog"
        file: "src/content/pages/blog.yaml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Featured Posts"
            name: "featured_posts"
            widget: "list"
            field:
              label: "Post Title"
              name: "title"
              widget: "string"